# [colors.bright]
# black = "#424242"
# blue = "#8DA3B9"
# cyan = "#8AA6A2"
# green = "#8C977D"
# magenta = "#A988B0"
# red = "#B66467"
# white = "#E8E3E3"
# yellow = "#D9BC8C"
#
# [colors.normal]
# black = "#151515"
# blue = "#8DA3B9"
# cyan = "#8AA6A2"
# green = "#8C977D"
# magenta = "#A988B0"
# red = "#B66467"
# white = "#E8E3E3"
# yellow = "#D9BC8C"
#
# [colors.primary]
# background = "#151515"
# foreground = "#E8E3E3"

# s3r0 theme
[colors.bright]
black = "#4A3637"
blue = "#535C5C"
cyan = "#6d715e"
green = "#7b8748"
magenta = "#775759"
red = "#d17b49"
white = "#c0b18b"
yellow = "#af865a"

[colors.normal]
black = "#4A3637"
blue = "#535C5C"
cyan = "#6d715e"
green = "#7b8748"
magenta = "#775759"
red = "#d17b49"
white = "#c0b18b"
yellow = "#af865a"

[colors.primary]
background = "#1f1f1f"
foreground = "#c0b18b"

[cursor]
# blink = true
style = "block"
thickness = 0.2
unfocused_hollow = false

[font]
size = 12

[font.bold]
family = "Terminess Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font"
style = "Italic"

[font.normal]
family = "Terminess Nerd Font"
style = "Medium"

[terminal.shell]
program = "/bin/zsh"

[window.padding]
x = 12
y = 12

# [window.scrolling]
# history = 15

[terminal]

