#!/usr/bin/env bash

# Record without audio
# ffmpeg -video_size 1366x768 -framerate 25 -f x11grab -i :0.0 output.mp4

# Record with audio
ffmpeg -video_size 1366x768 -framerate 25 -f x11grab -i :0.0 -f pulse -ac 2 -i hw:0 output.mkv
