#!/bin/sh
BROWSER="brave-bin"
url=$(sfeed_plain "$HOME/.sfeed/feeds/"* | /usr/local/bin/dmenu -l 35 -i | \
        sed -n 's@^.* \([a-zA-Z]*://\)\(.*\)$@\1\2@p')
test -n "${url}" && $BROWSER "${url}"
